### PR TITLE
Portainer 9443

### PR DESCRIPTION
**Pull request by germanium-git**

### CODE REVIEW

**Comment by germanium-git** [comment]
Terraform Plan:

```
module.cloudflare_dns.data.cloudflare_zone.zone: Reading...
module.cloudflare_dns.data.cloudflare_zone.zone: Read complete after 0s [id=7d3f63ac039666ab600b5796c54e7ba6]
oci_identity_compartment.k8s: Refreshing state... [id=ocid1.compartment.oc1..aaaaaaaa4bbfmz332ypqxr6icuitp54jj7czdp4qliuo575ytuqakppgtmra]
module.virtual_machine.data.oci_identity_availability_domains.ads: Reading...
module.virtual_network.oci_core_vcn.vcn["vcn1"]: Refreshing state... [id=ocid1.vcn.oc1.eu-frankfurt-1.amaaaaaaic6ifviawy53vzv7ylnbovxzlk6gdl3wj62qt7pazvsl3pinvxiq]
module.virtual_machine.data.oci_identity_availability_domains.ads: Read complete after 0s [id=IdentityAvailabilityDomainsDataSource-2220574233]
module.virtual_network.oci_core_internet_gateway.igw["vcn1"]: Refreshing state... [id=ocid1.internetgateway.oc1.eu-frankfurt-1.aaaaaaaafkt7nrvasfyvu4a7daqfqskkfh4vmbqpye7qr35abqnhrumie32a]
module.virtual_network.oci_core_network_security_group.nsg["vcn1"]: Refreshing state... [id=ocid1.networksecuritygroup.oc1.eu-frankfurt-1.aaaaaaaaphiusldsxpmy7odws7mwaitxvfeu52ntgbb2vkwe7fzhvyckb45q]
module.virtual_network.oci_core_network_security_group_security_rule.nsg_rule["rule2"]: Refreshing state... [id=73C8D4]
module.virtual_network.oci_core_network_security_group_security_rule.nsg_rule["rule1"]: Refreshing state... [id=96F721]
module.virtual_network.oci_core_network_security_group_security_rule.nsg_rule["rule3"]: Refreshing state... [id=868C1D]
module.virtual_network.oci_core_route_table.rt["vcn1"]: Refreshing state... [id=ocid1.routetable.oc1.eu-frankfurt-1.aaaaaaaa5jyv5xby72ed73eqsxt3t7o6z7symzmk3we5rhpongsnakijdzba]
module.virtual_network.oci_core_subnet.subnet["subnet1"]: Refreshing state... [id=ocid1.subnet.oc1.eu-frankfurt-1.aaaaaaaatfy3s5otqei4lcl7czf6jk7bliptcfwx4e35otvnd5muldjqutea]
module.virtual_machine.oci_core_volume.volume["worker1"]: Refreshing state... [id=ocid1.volume.oc1.eu-frankfurt-1.abtheljtwg7cmno4sc2puykujokfdwsk4odenr6sxgu5uktoeec73dae6zna]
module.virtual_machine.oci_core_volume.volume["neptun"]: Refreshing state... [id=ocid1.volume.oc1.eu-frankfurt-1.abtheljtkpphy4wpwhwcwrncy7bhpvqqu4m7genozusxg6pusrn4onw3hhda]
module.virtual_machine.oci_core_instance.vm["worker1"]: Refreshing state... [id=ocid1.instance.oc1.eu-frankfurt-1.antheljtic6ifvicyrvcdxqz6zmx6ahdsk44e4q23h6zabdlvo2csswwy57a]
module.virtual_machine.oci_core_instance.vm["neptun"]: Refreshing state... [id=ocid1.instance.oc1.eu-frankfurt-1.antheljtic6ifvic2axwrldfkhdr4rny6al36crdhwgigyat3tomzwszbb4q]
module.virtual_machine.oci_core_volume_attachment.volume_attachment["worker1"]: Refreshing state... [id=ocid1.volumeattachment.oc1.eu-frankfurt-1.antheljtic6ifvicl3uex6qjmrdvm4vqkyb3xfmceru6xzaids6owd2i2a7a]
module.virtual_machine.oci_core_volume_attachment.volume_attachment["neptun"]: Refreshing state... [id=ocid1.volumeattachment.oc1.eu-frankfurt-1.antheljtic6ifvic4vabntmpb4bzebab7k3xcwgfbtgju2qlji7cucvmwqgq]
module.cloudflare_dns.cloudflare_record.a_record["neptun"]: Refreshing state... [id=4f6c4e6f143366685cd9e54a37db35e9]
module.cloudflare_dns.cloudflare_record.a_record["worker1"]: Refreshing state... [id=85b2b2202a344df108f0d1f90ab7a0c6]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.virtual_network.oci_core_network_security_group_security_rule.nsg_rule["rule3"] will be updated in-place
  ~ resource "oci_core_network_security_group_security_rule" "nsg_rule" {
        id                        = "868C1D"
        # (9 unchanged attributes hidden)

      ~ tcp_options {
          ~ destination_port_range {
              ~ max = 9000 -> 9443
              ~ min = 9000 -> 9443
            }
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

Plan saved to GH artifacts.

**Review by petr-jamf — DISMISSED** [review]

**Comment by germanium-git** [comment]
Terraform Apply:

```
module.virtual_network.oci_core_network_security_group_security_rule.nsg_rule["rule3"]: Modifying... [id=868C1D]
module.virtual_network.oci_core_network_security_group_security_rule.nsg_rule["rule3"]: Modifications complete after 0s [id=868C1D]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.

Outputs:

vm_public_ip = {
  "neptun" = "158.180.17.167"
  "worker1" = "130.162.52.123"
}
```

**Comment by germanium-git** [comment]
Terraform Plan:

```
module.cloudflare_dns.data.cloudflare_zone.zone: Reading...
oci_identity_compartment.k8s: Refreshing state... [id=ocid1.compartment.oc1..aaaaaaaa4bbfmz332ypqxr6icuitp54jj7czdp4qliuo575ytuqakppgtmra]
module.cloudflare_dns.data.cloudflare_zone.zone: Read complete after 1s [id=7d3f63ac039666ab600b5796c54e7ba6]
module.virtual_machine.data.oci_identity_availability_domains.ads: Reading...
module.virtual_network.oci_core_vcn.vcn["vcn1"]: Refreshing state... [id=ocid1.vcn.oc1.eu-frankfurt-1.amaaaaaaic6ifviawy53vzv7ylnbovxzlk6gdl3wj62qt7pazvsl3pinvxiq]
module.virtual_machine.data.oci_identity_availability_domains.ads: Read complete after 0s [id=IdentityAvailabilityDomainsDataSource-2220574233]
module.virtual_network.oci_core_network_security_group.nsg["vcn1"]: Refreshing state... [id=ocid1.networksecuritygroup.oc1.eu-frankfurt-1.aaaaaaaaphiusldsxpmy7odws7mwaitxvfeu52ntgbb2vkwe7fzhvyckb45q]
module.virtual_network.oci_core_internet_gateway.igw["vcn1"]: Refreshing state... [id=ocid1.internetgateway.oc1.eu-frankfurt-1.aaaaaaaafkt7nrvasfyvu4a7daqfqskkfh4vmbqpye7qr35abqnhrumie32a]
module.virtual_network.oci_core_network_security_group_security_rule.nsg_rule["rule1"]: Refreshing state... [id=96F721]
module.virtual_network.oci_core_network_security_group_security_rule.nsg_rule["rule3"]: Refreshing state... [id=868C1D]
module.virtual_network.oci_core_network_security_group_security_rule.nsg_rule["rule2"]: Refreshing state... [id=73C8D4]
module.virtual_network.oci_core_route_table.rt["vcn1"]: Refreshing state... [id=ocid1.routetable.oc1.eu-frankfurt-1.aaaaaaaa5jyv5xby72ed73eqsxt3t7o6z7symzmk3we5rhpongsnakijdzba]
module.virtual_network.oci_core_subnet.subnet["subnet1"]: Refreshing state... [id=ocid1.subnet.oc1.eu-frankfurt-1.aaaaaaaatfy3s5otqei4lcl7czf6jk7bliptcfwx4e35otvnd5muldjqutea]
module.virtual_machine.oci_core_volume.volume["neptun"]: Refreshing state... [id=ocid1.volume.oc1.eu-frankfurt-1.abtheljtkpphy4wpwhwcwrncy7bhpvqqu4m7genozusxg6pusrn4onw3hhda]
module.virtual_machine.oci_core_volume.volume["worker1"]: Refreshing state... [id=ocid1.volume.oc1.eu-frankfurt-1.abtheljtwg7cmno4sc2puykujokfdwsk4odenr6sxgu5uktoeec73dae6zna]
module.virtual_machine.oci_core_instance.vm["worker1"]: Refreshing state... [id=ocid1.instance.oc1.eu-frankfurt-1.antheljtic6ifvicyrvcdxqz6zmx6ahdsk44e4q23h6zabdlvo2csswwy57a]
module.virtual_machine.oci_core_instance.vm["neptun"]: Refreshing state... [id=ocid1.instance.oc1.eu-frankfurt-1.antheljtic6ifvic2axwrldfkhdr4rny6al36crdhwgigyat3tomzwszbb4q]
module.virtual_machine.oci_core_volume_attachment.volume_attachment["neptun"]: Refreshing state... [id=ocid1.volumeattachment.oc1.eu-frankfurt-1.antheljtic6ifvic4vabntmpb4bzebab7k3xcwgfbtgju2qlji7cucvmwqgq]
module.virtual_machine.oci_core_volume_attachment.volume_attachment["worker1"]: Refreshing state... [id=ocid1.volumeattachment.oc1.eu-frankfurt-1.antheljtic6ifvicl3uex6qjmrdvm4vqkyb3xfmceru6xzaids6owd2i2a7a]
module.cloudflare_dns.cloudflare_record.a_record["worker1"]: Refreshing state... [id=85b2b2202a344df108f0d1f90ab7a0c6]
module.cloudflare_dns.cloudflare_record.a_record["neptun"]: Refreshing state... [id=4f6c4e6f143366685cd9e54a37db35e9]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # module.virtual_network.oci_core_network_security_group_security_rule.nsg_rule["rule4"] will be created
  + resource "oci_core_network_security_group_security_rule" "nsg_rule" {
      + description               = "socat acme.sh"
      + destination               = (known after apply)
      + destination_type          = (known after apply)
      + direction                 = "INGRESS"
      + id                        = (known after apply)
      + is_valid                  = (known after apply)
      + network_security_group_id = "ocid1.networksecuritygroup.oc1.eu-frankfurt-1.aaaaaaaaphiusldsxpmy7odws7mwaitxvfeu52ntgbb2vkwe7fzhvyckb45q"
      + protocol                  = "6"
      + source                    = "*"
      + source_type               = "CIDR_BLOCK"
      + stateless                 = false
      + time_created              = (known after apply)

      + tcp_options {
          + destination_port_range {
              + max = 80
              + min = 80
            }
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

Plan saved to GH artifacts.

**Review by petr-jamf — DISMISSED** [review]

**Comment by germanium-git** [comment]
Terraform Plan:

```
module.cloudflare_dns.data.cloudflare_zone.zone: Reading...
module.cloudflare_dns.data.cloudflare_zone.zone: Read complete after 0s [id=7d3f63ac039666ab600b5796c54e7ba6]
oci_identity_compartment.k8s: Refreshing state... [id=ocid1.compartment.oc1..aaaaaaaa4bbfmz332ypqxr6icuitp54jj7czdp4qliuo575ytuqakppgtmra]
module.virtual_machine.data.oci_identity_availability_domains.ads: Reading...
module.virtual_network.oci_core_vcn.vcn["vcn1"]: Refreshing state... [id=ocid1.vcn.oc1.eu-frankfurt-1.amaaaaaaic6ifviawy53vzv7ylnbovxzlk6gdl3wj62qt7pazvsl3pinvxiq]
module.virtual_machine.data.oci_identity_availability_domains.ads: Read complete after 0s [id=IdentityAvailabilityDomainsDataSource-2220574233]
module.virtual_network.oci_core_internet_gateway.igw["vcn1"]: Refreshing state... [id=ocid1.internetgateway.oc1.eu-frankfurt-1.aaaaaaaafkt7nrvasfyvu4a7daqfqskkfh4vmbqpye7qr35abqnhrumie32a]
module.virtual_network.oci_core_network_security_group.nsg["vcn1"]: Refreshing state... [id=ocid1.networksecuritygroup.oc1.eu-frankfurt-1.aaaaaaaaphiusldsxpmy7odws7mwaitxvfeu52ntgbb2vkwe7fzhvyckb45q]
module.virtual_network.oci_core_network_security_group_security_rule.nsg_rule["rule1"]: Refreshing state... [id=96F721]
module.virtual_network.oci_core_network_security_group_security_rule.nsg_rule["rule3"]: Refreshing state... [id=868C1D]
module.virtual_network.oci_core_network_security_group_security_rule.nsg_rule["rule2"]: Refreshing state... [id=73C8D4]
module.virtual_network.oci_core_route_table.rt["vcn1"]: Refreshing state... [id=ocid1.routetable.oc1.eu-frankfurt-1.aaaaaaaa5jyv5xby72ed73eqsxt3t7o6z7symzmk3we5rhpongsnakijdzba]
module.virtual_network.oci_core_subnet.subnet["subnet1"]: Refreshing state... [id=ocid1.subnet.oc1.eu-frankfurt-1.aaaaaaaatfy3s5otqei4lcl7czf6jk7bliptcfwx4e35otvnd5muldjqutea]
module.virtual_machine.oci_core_volume.volume["neptun"]: Refreshing state... [id=ocid1.volume.oc1.eu-frankfurt-1.abtheljtkpphy4wpwhwcwrncy7bhpvqqu4m7genozusxg6pusrn4onw3hhda]
module.virtual_machine.oci_core_volume.volume["worker1"]: Refreshing state... [id=ocid1.volume.oc1.eu-frankfurt-1.abtheljtwg7cmno4sc2puykujokfdwsk4odenr6sxgu5uktoeec73dae6zna]
module.virtual_machine.oci_core_instance.vm["worker1"]: Refreshing state... [id=ocid1.instance.oc1.eu-frankfurt-1.antheljtic6ifvicyrvcdxqz6zmx6ahdsk44e4q23h6zabdlvo2csswwy57a]
module.virtual_machine.oci_core_instance.vm["neptun"]: Refreshing state... [id=ocid1.instance.oc1.eu-frankfurt-1.antheljtic6ifvic2axwrldfkhdr4rny6al36crdhwgigyat3tomzwszbb4q]
module.virtual_machine.oci_core_volume_attachment.volume_attachment["worker1"]: Refreshing state... [id=ocid1.volumeattachment.oc1.eu-frankfurt-1.antheljtic6ifvicl3uex6qjmrdvm4vqkyb3xfmceru6xzaids6owd2i2a7a]
module.virtual_machine.oci_core_volume_attachment.volume_attachment["neptun"]: Refreshing state... [id=ocid1.volumeattachment.oc1.eu-frankfurt-1.antheljtic6ifvic4vabntmpb4bzebab7k3xcwgfbtgju2qlji7cucvmwqgq]
module.cloudflare_dns.cloudflare_record.a_record["neptun"]: Refreshing state... [id=4f6c4e6f143366685cd9e54a37db35e9]
module.cloudflare_dns.cloudflare_record.a_record["worker1"]: Refreshing state... [id=85b2b2202a344df108f0d1f90ab7a0c6]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # module.virtual_network.oci_core_network_security_group_security_rule.nsg_rule["rule4"] will be created
  + resource "oci_core_network_security_group_security_rule" "nsg_rule" {
      + description               = "socat acme.sh"
      + destination               = (known after apply)
      + destination_type          = (known after apply)
      + direction                 = "INGRESS"
      + id                        = (known after apply)
      + is_valid                  = (known after apply)
      + network_security_group_id = "ocid1.networksecuritygroup.oc1.eu-frankfurt-1.aaaaaaaaphiusldsxpmy7odws7mwaitxvfeu52ntgbb2vkwe7fzhvyckb45q"
      + protocol                  = "6"
      + source                    = "0.0.0.0/0"
      + source_type               = "CIDR_BLOCK"
      + stateless                 = false
      + time_created              = (known after apply)

      + tcp_options {
          + destination_port_range {
              + max = 80
              + min = 80
            }
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

Plan saved to GH artifacts.

**Review by petr-jamf — APPROVED** [review]

**Comment by germanium-git** [comment]
Terraform Apply:

```
module.virtual_network.oci_core_network_security_group_security_rule.nsg_rule["rule4"]: Creating...
module.virtual_network.oci_core_network_security_group_security_rule.nsg_rule["rule4"]: Creation complete after 1s [id=C61567]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

vm_public_ip = {
  "neptun" = "158.180.17.167"
  "worker1" = "130.162.52.123"
}
```

**Pull request merged**
