### PR TITLE
subnets uncommented in module

### PR DESCRIPTION
**Pull request by germanium-git**

### CODE REVIEW

**Comment by germanium-git** [comment]
Terraform Plan:

```
oci_identity_compartment.k8s: Refreshing state... [id=ocid1.compartment.oc1..aaaaaaaa4bbfmz332ypqxr6icuitp54jj7czdp4qliuo575ytuqakppgtmra]
module.virtual_network.oci_core_vcn.vcn["vcn1"]: Refreshing state... [id=ocid1.vcn.oc1.eu-frankfurt-1.amaaaaaaic6ifviaeoaecu6uwycqmey7fx557mpjsj2cq2m35l5czm66to6a]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # module.virtual_network.oci_core_internet_gateway.igw["vcn1"] will be created
  + resource "oci_core_internet_gateway" "igw" {
      + compartment_id = "ocid1.tenancy.oc1..aaaaaaaao7q2d72t4s3fe2wjrthjlux4eeazjbh4wkiilmdg4t7fd5jdn5ya"
      + defined_tags   = (known after apply)
      + display_name   = "vcn_01-igw"
      + enabled        = true
      + freeform_tags  = (known after apply)
      + id             = (known after apply)
      + route_table_id = (known after apply)
      + state          = (known after apply)
      + time_created   = (known after apply)
      + vcn_id         = "ocid1.vcn.oc1.eu-frankfurt-1.amaaaaaaic6ifviaeoaecu6uwycqmey7fx557mpjsj2cq2m35l5czm66to6a"
    }

  # module.virtual_network.oci_core_network_security_group.nsg["vcn1"] will be created
  + resource "oci_core_network_security_group" "nsg" {
      + compartment_id = "ocid1.tenancy.oc1..aaaaaaaao7q2d72t4s3fe2wjrthjlux4eeazjbh4wkiilmdg4t7fd5jdn5ya"
      + defined_tags   = (known after apply)
      + display_name   = "vcn_01-nsg"
      + freeform_tags  = (known after apply)
      + id             = (known after apply)
      + state          = (known after apply)
      + time_created   = (known after apply)
      + vcn_id         = "ocid1.vcn.oc1.eu-frankfurt-1.amaaaaaaic6ifviaeoaecu6uwycqmey7fx557mpjsj2cq2m35l5czm66to6a"
    }

  # module.virtual_network.oci_core_network_security_group_security_rule.nsg_rule["rule1"] will be created
  + resource "oci_core_network_security_group_security_rule" "nsg_rule" {
      + description               = "test rule"
      + destination               = (known after apply)
      + destination_type          = (known after apply)
      + direction                 = "INGRESS"
      + id                        = (known after apply)
      + is_valid                  = (known after apply)
      + network_security_group_id = (known after apply)
      + protocol                  = "6"
      + source                    = "10.20.30.40"
      + source_type               = "CIDR_BLOCK"
      + stateless                 = false
      + time_created              = (known after apply)

      + tcp_options {
          + destination_port_range {
              + max = 200
              + min = 100
            }
        }
    }

  # module.virtual_network.oci_core_route_table.rt["vcn1"] will be created
  + resource "oci_core_route_table" "rt" {
      + compartment_id = "ocid1.tenancy.oc1..aaaaaaaao7q2d72t4s3fe2wjrthjlux4eeazjbh4wkiilmdg4t7fd5jdn5ya"
      + defined_tags   = (known after apply)
      + display_name   = "Default RT for vcn_01"
      + freeform_tags  = (known after apply)
      + id             = (known after apply)
      + state          = (known after apply)
      + time_created   = (known after apply)
      + vcn_id         = "ocid1.vcn.oc1.eu-frankfurt-1.amaaaaaaic6ifviaeoaecu6uwycqmey7fx557mpjsj2cq2m35l5czm66to6a"

      + route_rules {
          + cidr_block        = "0.0.0.0/0"
          + description       = (known after apply)
          + destination       = (known after apply)
          + destination_type  = (known after apply)
          + network_entity_id = (known after apply)
          + route_type        = (known after apply)
        }
    }

  # module.virtual_network.oci_core_subnet.subnet["subnet1"] will be created
  + resource "oci_core_subnet" "subnet" {
      + availability_domain        = (known after apply)
      + cidr_block                 = "10.1.1.0/24"
      + compartment_id             = "ocid1.tenancy.oc1..aaaaaaaao7q2d72t4s3fe2wjrthjlux4eeazjbh4wkiilmdg4t7fd5jdn5ya"
      + defined_tags               = (known after apply)
      + dhcp_options_id            = (known after apply)
      + display_name               = "subnet1"
      + dns_label                  = (known after apply)
      + freeform_tags              = (known after apply)
      + id                         = (known after apply)
      + ipv6cidr_block             = (known after apply)
      + ipv6cidr_blocks            = (known after apply)
      + ipv6virtual_router_ip      = (known after apply)
      + prohibit_internet_ingress  = (known after apply)
      + prohibit_public_ip_on_vnic = (known after apply)
      + route_table_id             = (known after apply)
      + security_list_ids          = [
          + "ocid1.securitylist.oc1.eu-frankfurt-1.aaaaaaaa743oe4uuub5n5u4mi4mz7w7q5t7hox4yy4dbn3sgj4mfrsnwalqq",
        ]
      + state                      = (known after apply)
      + subnet_domain_name         = (known after apply)
      + time_created               = (known after apply)
      + vcn_id                     = "ocid1.vcn.oc1.eu-frankfurt-1.amaaaaaaic6ifviaeoaecu6uwycqmey7fx557mpjsj2cq2m35l5czm66to6a"
      + virtual_router_ip          = (known after apply)
      + virtual_router_mac         = (known after apply)
    }

Plan: 5 to add, 0 to change, 0 to destroy.
```

Plan saved to GH artifacts.

**Review by petr-jamf — DISMISSED** [review]

**Comment by germanium-git** [comment]
Terraform Plan:

```
oci_identity_compartment.k8s: Refreshing state... [id=ocid1.compartment.oc1..aaaaaaaa4bbfmz332ypqxr6icuitp54jj7czdp4qliuo575ytuqakppgtmra]
module.virtual_network.oci_core_vcn.vcn["vcn1"]: Refreshing state... [id=ocid1.vcn.oc1.eu-frankfurt-1.amaaaaaaic6ifviaeoaecu6uwycqmey7fx557mpjsj2cq2m35l5czm66to6a]
module.virtual_network.oci_core_internet_gateway.igw["vcn1"]: Refreshing state... [id=ocid1.internetgateway.oc1.eu-frankfurt-1.aaaaaaaatkiuijvp3iqbqnkdtznubouu2tg2verx24tgajrkoh5kh4znr7sa]
module.virtual_network.oci_core_network_security_group.nsg["vcn1"]: Refreshing state... [id=ocid1.networksecuritygroup.oc1.eu-frankfurt-1.aaaaaaaa77qzf3kjaksjekmwpf7ljfaohaclwaklrzztsea4umy5usxnl4xa]
module.virtual_network.oci_core_route_table.rt["vcn1"]: Refreshing state... [id=ocid1.routetable.oc1.eu-frankfurt-1.aaaaaaaayo35y4z5ptradj66364ykxoqytm6mfnqfahiwboyevwscpq4zf3a]
module.virtual_network.oci_core_subnet.subnet["subnet1"]: Refreshing state... [id=ocid1.subnet.oc1.eu-frankfurt-1.aaaaaaaaxk5c2nrlrmqdyvj7rprsp57wmfwdvqcloexfo4omsi3soafnpfrq]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create
  ~ update in-place

Terraform will perform the following actions:

  # module.virtual_network.oci_core_internet_gateway.igw["vcn1"] will be updated in-place
  ~ resource "oci_core_internet_gateway" "igw" {
      ~ defined_tags   = {
          - "Oracle-Tags.CreatedBy" = "default/petr.nemec@gmx.com" -> null
          - "Oracle-Tags.CreatedOn" = "2023-06-02T09:37:50.584Z" -> null
        }
        id             = "ocid1.internetgateway.oc1.eu-frankfurt-1.aaaaaaaatkiuijvp3iqbqnkdtznubouu2tg2verx24tgajrkoh5kh4znr7sa"
        # (7 unchanged attributes hidden)
    }

  # module.virtual_network.oci_core_network_security_group_security_rule.nsg_rule["rule1"] will be created
  + resource "oci_core_network_security_group_security_rule" "nsg_rule" {
      + description               = "test rule"
      + destination               = (known after apply)
      + destination_type          = (known after apply)
      + direction                 = "INGRESS"
      + id                        = (known after apply)
      + is_valid                  = (known after apply)
      + network_security_group_id = "ocid1.networksecuritygroup.oc1.eu-frankfurt-1.aaaaaaaa77qzf3kjaksjekmwpf7ljfaohaclwaklrzztsea4umy5usxnl4xa"
      + protocol                  = "6"
      + source                    = "10.20.30.40/32"
      + source_type               = "CIDR_BLOCK"
      + stateless                 = false
      + time_created              = (known after apply)

      + tcp_options {
          + destination_port_range {
              + max = 200
              + min = 100
            }
        }
    }

  # module.virtual_network.oci_core_route_table.rt["vcn1"] will be updated in-place
  ~ resource "oci_core_route_table" "rt" {
      ~ defined_tags   = {
          - "Oracle-Tags.CreatedBy" = "default/petr.nemec@gmx.com" -> null
          - "Oracle-Tags.CreatedOn" = "2023-06-02T09:37:51.644Z" -> null
        }
        id             = "ocid1.routetable.oc1.eu-frankfurt-1.aaaaaaaayo35y4z5ptradj66364ykxoqytm6mfnqfahiwboyevwscpq4zf3a"
        # (6 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

Plan: 1 to add, 2 to change, 0 to destroy.

Warning: Argument is deprecated

  with module.virtual_network.oci_core_route_table.rt["vcn1"],
  on modules/virtualNetwork/virtualNetwork.tf line 36, in resource "oci_core_route_table" "rt":
  36: resource oci_core_route_table "rt" {

The 'cidr_block' field has been deprecated. Please use 'destination' instead.
```

Plan saved to GH artifacts.

**Review by petr-jamf — DISMISSED** [review]

**Comment by germanium-git** [comment]
Terraform Apply:

```
module.virtual_network.oci_core_network_security_group_security_rule.nsg_rule["rule1"]: Creating...
module.virtual_network.oci_core_internet_gateway.igw["vcn1"]: Modifying... [id=ocid1.internetgateway.oc1.eu-frankfurt-1.aaaaaaaatkiuijvp3iqbqnkdtznubouu2tg2verx24tgajrkoh5kh4znr7sa]
module.virtual_network.oci_core_internet_gateway.igw["vcn1"]: Modifications complete after 1s [id=ocid1.internetgateway.oc1.eu-frankfurt-1.aaaaaaaatkiuijvp3iqbqnkdtznubouu2tg2verx24tgajrkoh5kh4znr7sa]
module.virtual_network.oci_core_route_table.rt["vcn1"]: Modifying... [id=ocid1.routetable.oc1.eu-frankfurt-1.aaaaaaaayo35y4z5ptradj66364ykxoqytm6mfnqfahiwboyevwscpq4zf3a]
module.virtual_network.oci_core_network_security_group_security_rule.nsg_rule["rule1"]: Creation complete after 1s [id=F9258D]
module.virtual_network.oci_core_route_table.rt["vcn1"]: Modifications complete after 0s [id=ocid1.routetable.oc1.eu-frankfurt-1.aaaaaaaayo35y4z5ptradj66364ykxoqytm6mfnqfahiwboyevwscpq4zf3a]

Warning: Argument is deprecated

  with module.virtual_network.oci_core_route_table.rt["vcn1"],
  on modules/virtualNetwork/virtualNetwork.tf line 36, in resource "oci_core_route_table" "rt":
  36: resource oci_core_route_table "rt" {

The 'cidr_block' field has been deprecated. Please use 'destination' instead.

Apply complete! Resources: 1 added, 2 changed, 0 destroyed.
```

**Comment by germanium-git** [comment]
Terraform Plan:

```
oci_identity_compartment.k8s: Refreshing state... [id=ocid1.compartment.oc1..aaaaaaaa4bbfmz332ypqxr6icuitp54jj7czdp4qliuo575ytuqakppgtmra]
module.virtual_network.oci_core_vcn.vcn["vcn1"]: Refreshing state... [id=ocid1.vcn.oc1.eu-frankfurt-1.amaaaaaaic6ifviaeoaecu6uwycqmey7fx557mpjsj2cq2m35l5czm66to6a]
module.virtual_network.oci_core_network_security_group.nsg["vcn1"]: Refreshing state... [id=ocid1.networksecuritygroup.oc1.eu-frankfurt-1.aaaaaaaa77qzf3kjaksjekmwpf7ljfaohaclwaklrzztsea4umy5usxnl4xa]
module.virtual_network.oci_core_internet_gateway.igw["vcn1"]: Refreshing state... [id=ocid1.internetgateway.oc1.eu-frankfurt-1.aaaaaaaatkiuijvp3iqbqnkdtznubouu2tg2verx24tgajrkoh5kh4znr7sa]
module.virtual_network.oci_core_network_security_group_security_rule.nsg_rule["rule1"]: Refreshing state... [id=F9258D]
module.virtual_network.oci_core_route_table.rt["vcn1"]: Refreshing state... [id=ocid1.routetable.oc1.eu-frankfurt-1.aaaaaaaayo35y4z5ptradj66364ykxoqytm6mfnqfahiwboyevwscpq4zf3a]
module.virtual_network.oci_core_subnet.subnet["subnet1"]: Refreshing state... [id=ocid1.subnet.oc1.eu-frankfurt-1.aaaaaaaaxk5c2nrlrmqdyvj7rprsp57wmfwdvqcloexfo4omsi3soafnpfrq]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration
and found no differences, so no changes are needed.
```

Plan saved to GH artifacts.

**Review by petr-jamf — DISMISSED** [review]

**Comment by germanium-git** [comment]
Terraform Apply:

```

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

**Comment by germanium-git** [comment]
Terraform Plan:

```
oci_identity_compartment.k8s: Refreshing state... [id=ocid1.compartment.oc1..aaaaaaaa4bbfmz332ypqxr6icuitp54jj7czdp4qliuo575ytuqakppgtmra]
module.virtual_network.oci_core_vcn.vcn["vcn1"]: Refreshing state... [id=ocid1.vcn.oc1.eu-frankfurt-1.amaaaaaaic6ifviaeoaecu6uwycqmey7fx557mpjsj2cq2m35l5czm66to6a]
module.virtual_network.oci_core_network_security_group.nsg["vcn1"]: Refreshing state... [id=ocid1.networksecuritygroup.oc1.eu-frankfurt-1.aaaaaaaa77qzf3kjaksjekmwpf7ljfaohaclwaklrzztsea4umy5usxnl4xa]
module.virtual_network.oci_core_internet_gateway.igw["vcn1"]: Refreshing state... [id=ocid1.internetgateway.oc1.eu-frankfurt-1.aaaaaaaatkiuijvp3iqbqnkdtznubouu2tg2verx24tgajrkoh5kh4znr7sa]
module.virtual_network.oci_core_route_table.rt["vcn1"]: Refreshing state... [id=ocid1.routetable.oc1.eu-frankfurt-1.aaaaaaaayo35y4z5ptradj66364ykxoqytm6mfnqfahiwboyevwscpq4zf3a]
module.virtual_network.oci_core_network_security_group_security_rule.nsg_rule["rule1"]: Refreshing state... [id=F9258D]
module.virtual_network.oci_core_subnet.subnet["subnet1"]: Refreshing state... [id=ocid1.subnet.oc1.eu-frankfurt-1.aaaaaaaaxk5c2nrlrmqdyvj7rprsp57wmfwdvqcloexfo4omsi3soafnpfrq]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration
and found no differences, so no changes are needed.
```

Plan saved to GH artifacts.

**Review by petr-jamf — APPROVED** [review]

**Comment by germanium-git** [comment]
Terraform Apply:

```

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

**Pull request merged**
