### PR TITLE
module virtualNetwork

### PR DESCRIPTION
**Pull request by germanium-git**

### CODE REVIEW

**Comment by germanium-git** [comment]
Terraform Plan:

```
oci_core_vcn.vcn1: Refreshing state... [id=ocid1.vcn.oc1.eu-frankfurt-1.amaaaaaaic6ifviaceekdqugkjpwl4b44z7othlgv5mnyjgvic3r6zoaqqva]
oci_identity_compartment.k8s: Refreshing state... [id=ocid1.compartment.oc1..aaaaaaaa4bbfmz332ypqxr6icuitp54jj7czdp4qliuo575ytuqakppgtmra]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create
  - destroy

Terraform will perform the following actions:

  # oci_core_vcn.vcn1 will be destroyed
  # (because oci_core_vcn.vcn1 is not in configuration)
  - resource "oci_core_vcn" "vcn1" {
      - byoipv6cidr_blocks       = [] -> null
      - cidr_block               = "10.1.0.0/16" -> null
      - cidr_blocks              = [
          - "10.1.0.0/16",
        ] -> null
      - compartment_id           = "ocid1.tenancy.oc1..aaaaaaaao7q2d72t4s3fe2wjrthjlux4eeazjbh4wkiilmdg4t7fd5jdn5ya" -> null
      - default_dhcp_options_id  = "ocid1.dhcpoptions.oc1.eu-frankfurt-1.aaaaaaaaitisy5xu4df4fc54hrfhdl5pv4mlzlew5w3oplhaorsadvtub7sa" -> null
      - default_route_table_id   = "ocid1.routetable.oc1.eu-frankfurt-1.aaaaaaaahcudu7s2mwgdcdvru2wazpybxdzvu2kejpyc6kko7ayyn73keksq" -> null
      - default_security_list_id = "ocid1.securitylist.oc1.eu-frankfurt-1.aaaaaaaahcy6hzn2m3xybltkg7ggfkkd24gy3bjqzaqrhrasjv4dmntd76pa" -> null
      - defined_tags             = {
          - "Oracle-Tags.CreatedBy" = "default/petr.nemec@gmx.com"
          - "Oracle-Tags.CreatedOn" = "2023-05-30T08:24:41.480Z"
        } -> null
      - display_name             = "k8s-vcn" -> null
      - freeform_tags            = {} -> null
      - id                       = "ocid1.vcn.oc1.eu-frankfurt-1.amaaaaaaic6ifviaceekdqugkjpwl4b44z7othlgv5mnyjgvic3r6zoaqqva" -> null
      - ipv6cidr_blocks          = [] -> null
      - ipv6private_cidr_blocks  = [] -> null
      - is_ipv6enabled           = false -> null
      - state                    = "AVAILABLE" -> null
      - time_created             = "2023-05-30 08:24:41.605 +0000 UTC" -> null
    }

  # module.virtual_network.oci_core_vcn.vcn["vcn1"] will be created
  + resource "oci_core_vcn" "vcn" {
      + byoipv6cidr_blocks               = (known after apply)
      + cidr_block                       = "10.1.0.0/16"
      + cidr_blocks                      = (known after apply)
      + compartment_id                   = "ocid1.tenancy.oc1..aaaaaaaao7q2d72t4s3fe2wjrthjlux4eeazjbh4wkiilmdg4t7fd5jdn5ya"
      + default_dhcp_options_id          = (known after apply)
      + default_route_table_id           = (known after apply)
      + default_security_list_id         = (known after apply)
      + defined_tags                     = (known after apply)
      + display_name                     = "vcn_01"
      + dns_label                        = (known after apply)
      + freeform_tags                    = (known after apply)
      + id                               = (known after apply)
      + ipv6cidr_blocks                  = (known after apply)
      + ipv6private_cidr_blocks          = (known after apply)
      + is_ipv6enabled                   = (known after apply)
      + is_oracle_gua_allocation_enabled = (known after apply)
      + state                            = (known after apply)
      + time_created                     = (known after apply)
      + vcn_domain_name                  = (known after apply)
    }

Plan: 1 to add, 0 to change, 1 to destroy.

Warning: Duplicate required provider

  on provider.tf line 6, in terraform:
   6:       hoci = {
   7:          source = "hashicorp/oci"
   8:     }

Provider hashicorp/oci with the local name "hoci" was implicitly required via
a configuration block as "oci". The provider configuration block name must
match the name used in required_providers.
```

Plan saved to GH artifacts.

**Comment by germanium-git** [comment]
Terraform Plan:

```
oci_core_vcn.vcn1: Refreshing state... [id=ocid1.vcn.oc1.eu-frankfurt-1.amaaaaaaic6ifviaceekdqugkjpwl4b44z7othlgv5mnyjgvic3r6zoaqqva]
oci_identity_compartment.k8s: Refreshing state... [id=ocid1.compartment.oc1..aaaaaaaa4bbfmz332ypqxr6icuitp54jj7czdp4qliuo575ytuqakppgtmra]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create
  - destroy

Terraform will perform the following actions:

  # oci_core_vcn.vcn1 will be destroyed
  # (because oci_core_vcn.vcn1 is not in configuration)
  - resource "oci_core_vcn" "vcn1" {
      - byoipv6cidr_blocks       = [] -> null
      - cidr_block               = "10.1.0.0/16" -> null
      - cidr_blocks              = [
          - "10.1.0.0/16",
        ] -> null
      - compartment_id           = "ocid1.tenancy.oc1..aaaaaaaao7q2d72t4s3fe2wjrthjlux4eeazjbh4wkiilmdg4t7fd5jdn5ya" -> null
      - default_dhcp_options_id  = "ocid1.dhcpoptions.oc1.eu-frankfurt-1.aaaaaaaaitisy5xu4df4fc54hrfhdl5pv4mlzlew5w3oplhaorsadvtub7sa" -> null
      - default_route_table_id   = "ocid1.routetable.oc1.eu-frankfurt-1.aaaaaaaahcudu7s2mwgdcdvru2wazpybxdzvu2kejpyc6kko7ayyn73keksq" -> null
      - default_security_list_id = "ocid1.securitylist.oc1.eu-frankfurt-1.aaaaaaaahcy6hzn2m3xybltkg7ggfkkd24gy3bjqzaqrhrasjv4dmntd76pa" -> null
      - defined_tags             = {
          - "Oracle-Tags.CreatedBy" = "default/petr.nemec@gmx.com"
          - "Oracle-Tags.CreatedOn" = "2023-05-30T08:24:41.480Z"
        } -> null
      - display_name             = "k8s-vcn" -> null
      - freeform_tags            = {} -> null
      - id                       = "ocid1.vcn.oc1.eu-frankfurt-1.amaaaaaaic6ifviaceekdqugkjpwl4b44z7othlgv5mnyjgvic3r6zoaqqva" -> null
      - ipv6cidr_blocks          = [] -> null
      - ipv6private_cidr_blocks  = [] -> null
      - is_ipv6enabled           = false -> null
      - state                    = "AVAILABLE" -> null
      - time_created             = "2023-05-30 08:24:41.605 +0000 UTC" -> null
    }

  # module.virtual_network.oci_core_vcn.vcn["vcn1"] will be created
  + resource "oci_core_vcn" "vcn" {
      + byoipv6cidr_blocks               = (known after apply)
      + cidr_block                       = "10.1.0.0/16"
      + cidr_blocks                      = (known after apply)
      + compartment_id                   = "ocid1.tenancy.oc1..aaaaaaaao7q2d72t4s3fe2wjrthjlux4eeazjbh4wkiilmdg4t7fd5jdn5ya"
      + default_dhcp_options_id          = (known after apply)
      + default_route_table_id           = (known after apply)
      + default_security_list_id         = (known after apply)
      + defined_tags                     = (known after apply)
      + display_name                     = "vcn_01"
      + dns_label                        = (known after apply)
      + freeform_tags                    = (known after apply)
      + id                               = (known after apply)
      + ipv6cidr_blocks                  = (known after apply)
      + ipv6private_cidr_blocks          = (known after apply)
      + is_ipv6enabled                   = (known after apply)
      + is_oracle_gua_allocation_enabled = (known after apply)
      + state                            = (known after apply)
      + time_created                     = (known after apply)
      + vcn_domain_name                  = (known after apply)
    }

Plan: 1 to add, 0 to change, 1 to destroy.

Warning: Duplicate required provider

  on compartment.tf line 1:
   1: resource "oci_identity_compartment" "k8s" {

Provider "registry.terraform.io/hashicorp/oci" was implicitly required via
resource "oci_identity_compartment.k8s", but listed in required_providers as
"hashi-oci". Either the local name in required_providers must match the
resource name, or the "hashi-oci" provider must be assigned within the
resource block.
```

Plan saved to GH artifacts.

**Comment by germanium-git** [comment]
Terraform Plan:

```
oci_core_vcn.vcn1: Refreshing state... [id=ocid1.vcn.oc1.eu-frankfurt-1.amaaaaaaic6ifviaceekdqugkjpwl4b44z7othlgv5mnyjgvic3r6zoaqqva]
oci_identity_compartment.k8s: Refreshing state... [id=ocid1.compartment.oc1..aaaaaaaa4bbfmz332ypqxr6icuitp54jj7czdp4qliuo575ytuqakppgtmra]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create
  - destroy

Terraform will perform the following actions:

  # oci_core_vcn.vcn1 will be destroyed
  # (because oci_core_vcn.vcn1 is not in configuration)
  - resource "oci_core_vcn" "vcn1" {
      - byoipv6cidr_blocks       = [] -> null
      - cidr_block               = "10.1.0.0/16" -> null
      - cidr_blocks              = [
          - "10.1.0.0/16",
        ] -> null
      - compartment_id           = "ocid1.tenancy.oc1..aaaaaaaao7q2d72t4s3fe2wjrthjlux4eeazjbh4wkiilmdg4t7fd5jdn5ya" -> null
      - default_dhcp_options_id  = "ocid1.dhcpoptions.oc1.eu-frankfurt-1.aaaaaaaaitisy5xu4df4fc54hrfhdl5pv4mlzlew5w3oplhaorsadvtub7sa" -> null
      - default_route_table_id   = "ocid1.routetable.oc1.eu-frankfurt-1.aaaaaaaahcudu7s2mwgdcdvru2wazpybxdzvu2kejpyc6kko7ayyn73keksq" -> null
      - default_security_list_id = "ocid1.securitylist.oc1.eu-frankfurt-1.aaaaaaaahcy6hzn2m3xybltkg7ggfkkd24gy3bjqzaqrhrasjv4dmntd76pa" -> null
      - defined_tags             = {
          - "Oracle-Tags.CreatedBy" = "default/petr.nemec@gmx.com"
          - "Oracle-Tags.CreatedOn" = "2023-05-30T08:24:41.480Z"
        } -> null
      - display_name             = "k8s-vcn" -> null
      - freeform_tags            = {} -> null
      - id                       = "ocid1.vcn.oc1.eu-frankfurt-1.amaaaaaaic6ifviaceekdqugkjpwl4b44z7othlgv5mnyjgvic3r6zoaqqva" -> null
      - ipv6cidr_blocks          = [] -> null
      - ipv6private_cidr_blocks  = [] -> null
      - is_ipv6enabled           = false -> null
      - state                    = "AVAILABLE" -> null
      - time_created             = "2023-05-30 08:24:41.605 +0000 UTC" -> null
    }

  # module.virtual_network.oci_core_vcn.vcn["vcn1"] will be created
  + resource "oci_core_vcn" "vcn" {
      + byoipv6cidr_blocks               = (known after apply)
      + cidr_block                       = "10.1.0.0/16"
      + cidr_blocks                      = (known after apply)
      + compartment_id                   = "ocid1.tenancy.oc1..aaaaaaaao7q2d72t4s3fe2wjrthjlux4eeazjbh4wkiilmdg4t7fd5jdn5ya"
      + default_dhcp_options_id          = (known after apply)
      + default_route_table_id           = (known after apply)
      + default_security_list_id         = (known after apply)
      + defined_tags                     = (known after apply)
      + display_name                     = "vcn_01"
      + dns_label                        = (known after apply)
      + freeform_tags                    = (known after apply)
      + id                               = (known after apply)
      + ipv6cidr_blocks                  = (known after apply)
      + ipv6private_cidr_blocks          = (known after apply)
      + is_ipv6enabled                   = (known after apply)
      + is_oracle_gua_allocation_enabled = (known after apply)
      + state                            = (known after apply)
      + time_created                     = (known after apply)
      + vcn_domain_name                  = (known after apply)
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```

Plan saved to GH artifacts.

**Comment by germanium-git** [comment]
Terraform Plan:

```
oci_core_vcn.vcn1: Refreshing state... [id=ocid1.vcn.oc1.eu-frankfurt-1.amaaaaaaic6ifviaceekdqugkjpwl4b44z7othlgv5mnyjgvic3r6zoaqqva]
oci_identity_compartment.k8s: Refreshing state... [id=ocid1.compartment.oc1..aaaaaaaa4bbfmz332ypqxr6icuitp54jj7czdp4qliuo575ytuqakppgtmra]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create
  - destroy

Terraform will perform the following actions:

  # oci_core_vcn.vcn1 will be destroyed
  # (because oci_core_vcn.vcn1 is not in configuration)
  - resource "oci_core_vcn" "vcn1" {
      - byoipv6cidr_blocks       = [] -> null
      - cidr_block               = "10.1.0.0/16" -> null
      - cidr_blocks              = [
          - "10.1.0.0/16",
        ] -> null
      - compartment_id           = "ocid1.tenancy.oc1..aaaaaaaao7q2d72t4s3fe2wjrthjlux4eeazjbh4wkiilmdg4t7fd5jdn5ya" -> null
      - default_dhcp_options_id  = "ocid1.dhcpoptions.oc1.eu-frankfurt-1.aaaaaaaaitisy5xu4df4fc54hrfhdl5pv4mlzlew5w3oplhaorsadvtub7sa" -> null
      - default_route_table_id   = "ocid1.routetable.oc1.eu-frankfurt-1.aaaaaaaahcudu7s2mwgdcdvru2wazpybxdzvu2kejpyc6kko7ayyn73keksq" -> null
      - default_security_list_id = "ocid1.securitylist.oc1.eu-frankfurt-1.aaaaaaaahcy6hzn2m3xybltkg7ggfkkd24gy3bjqzaqrhrasjv4dmntd76pa" -> null
      - defined_tags             = {
          - "Oracle-Tags.CreatedBy" = "default/petr.nemec@gmx.com"
          - "Oracle-Tags.CreatedOn" = "2023-05-30T08:24:41.480Z"
        } -> null
      - display_name             = "k8s-vcn" -> null
      - freeform_tags            = {} -> null
      - id                       = "ocid1.vcn.oc1.eu-frankfurt-1.amaaaaaaic6ifviaceekdqugkjpwl4b44z7othlgv5mnyjgvic3r6zoaqqva" -> null
      - ipv6cidr_blocks          = [] -> null
      - ipv6private_cidr_blocks  = [] -> null
      - is_ipv6enabled           = false -> null
      - state                    = "AVAILABLE" -> null
      - time_created             = "2023-05-30 08:24:41.605 +0000 UTC" -> null
    }

  # module.virtual_network.oci_core_vcn.vcn["vcn1"] will be created
  + resource "oci_core_vcn" "vcn" {
      + byoipv6cidr_blocks               = (known after apply)
      + cidr_block                       = "10.1.0.0/16"
      + cidr_blocks                      = (known after apply)
      + compartment_id                   = "ocid1.tenancy.oc1..aaaaaaaao7q2d72t4s3fe2wjrthjlux4eeazjbh4wkiilmdg4t7fd5jdn5ya"
      + default_dhcp_options_id          = (known after apply)
      + default_route_table_id           = (known after apply)
      + default_security_list_id         = (known after apply)
      + defined_tags                     = (known after apply)
      + display_name                     = "vcn_01"
      + dns_label                        = (known after apply)
      + freeform_tags                    = (known after apply)
      + id                               = (known after apply)
      + ipv6cidr_blocks                  = (known after apply)
      + ipv6private_cidr_blocks          = (known after apply)
      + is_ipv6enabled                   = (known after apply)
      + is_oracle_gua_allocation_enabled = (known after apply)
      + state                            = (known after apply)
      + time_created                     = (known after apply)
      + vcn_domain_name                  = (known after apply)
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```

Plan saved to GH artifacts.

**Review by petr-jamf — APPROVED** [review]

**Comment by germanium-git** [comment]
Terraform Apply:

```
oci_core_vcn.vcn1: Destroying... [id=ocid1.vcn.oc1.eu-frankfurt-1.amaaaaaaic6ifviaceekdqugkjpwl4b44z7othlgv5mnyjgvic3r6zoaqqva]
module.virtual_network.oci_core_vcn.vcn["vcn1"]: Creating...
oci_core_vcn.vcn1: Destruction complete after 1s
module.virtual_network.oci_core_vcn.vcn["vcn1"]: Creation complete after 1s [id=ocid1.vcn.oc1.eu-frankfurt-1.amaaaaaaic6ifviaeoaecu6uwycqmey7fx557mpjsj2cq2m35l5czm66to6a]

Apply complete! Resources: 1 added, 0 changed, 1 destroyed.
```

**Pull request merged**
