### PR TITLE
GH action rebase moved to workflows

### PR DESCRIPTION
**Pull request by germanium-git**

### CODE REVIEW

**Comment by germanium-git** [comment]
Terraform Plan:

```
oci_identity_compartment.k8s: Refreshing state... [id=ocid1.compartment.oc1..aaaaaaaa4bbfmz332ypqxr6icuitp54jj7czdp4qliuo575ytuqakppgtmra]
module.virtual_machine.data.oci_identity_availability_domains.ads: Reading...
module.virtual_network.oci_core_vcn.vcn["vcn1"]: Refreshing state... [id=ocid1.vcn.oc1.eu-frankfurt-1.amaaaaaaic6ifviaeoaecu6uwycqmey7fx557mpjsj2cq2m35l5czm66to6a]
module.virtual_machine.data.oci_identity_availability_domains.ads: Read complete after 0s [id=IdentityAvailabilityDomainsDataSource-2220574233]
module.virtual_network.oci_core_internet_gateway.igw["vcn1"]: Refreshing state... [id=ocid1.internetgateway.oc1.eu-frankfurt-1.aaaaaaaatkiuijvp3iqbqnkdtznubouu2tg2verx24tgajrkoh5kh4znr7sa]
module.virtual_network.oci_core_network_security_group.nsg["vcn1"]: Refreshing state... [id=ocid1.networksecuritygroup.oc1.eu-frankfurt-1.aaaaaaaa77qzf3kjaksjekmwpf7ljfaohaclwaklrzztsea4umy5usxnl4xa]
module.virtual_network.oci_core_network_security_group_security_rule.nsg_rule["rule1"]: Refreshing state... [id=F9258D]
module.virtual_network.oci_core_route_table.rt["vcn1"]: Refreshing state... [id=ocid1.routetable.oc1.eu-frankfurt-1.aaaaaaaayo35y4z5ptradj66364ykxoqytm6mfnqfahiwboyevwscpq4zf3a]
module.virtual_network.oci_core_subnet.subnet["subnet1"]: Refreshing state... [id=ocid1.subnet.oc1.eu-frankfurt-1.aaaaaaaaxk5c2nrlrmqdyvj7rprsp57wmfwdvqcloexfo4omsi3soafnpfrq]
module.virtual_machine.oci_core_instance.vm["worker1"]: Refreshing state... [id=ocid1.instance.oc1.eu-frankfurt-1.antheljtic6ifvicmwwhl2b55o4u2na6l2d6q2k7qib6k6buod6pmw6ojqsq]
module.virtual_machine.oci_core_instance.vm["worker2"]: Refreshing state... [id=ocid1.instance.oc1.eu-frankfurt-1.antheljtic6ifvic4pb5ps5nmwormfclzw73jukt4jo46xtmjwpytmxll5qq]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration
and found no differences, so no changes are needed.
```

Plan saved to GH artifacts.

**Review by petr-jamf — APPROVED** [review]

**Comment by germanium-git** [comment]
Terraform Apply:

```

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

vm_public_ip = {
  "worker1" = "130.162.57.92"
  "worker2" = "130.61.13.151"
}
```

**Pull request merged**
