### PR TITLE
CloudfFlare module

### PR DESCRIPTION
**Pull request by germanium-git**

### CODE REVIEW

**Comment by germanium-git** [comment]
Terraform Plan:

```
module.cloudflare_dns.data.cloudflare_zones.zone: Reading...
module.cloudflare_dns.data.cloudflare_zones.zone: Read complete after 0s [id=db02d579021ff238991a645e755dfb8b]
oci_identity_compartment.k8s: Refreshing state... [id=ocid1.compartment.oc1..aaaaaaaa4bbfmz332ypqxr6icuitp54jj7czdp4qliuo575ytuqakppgtmra]
module.virtual_machine.data.oci_identity_availability_domains.ads: Reading...
module.virtual_network.oci_core_vcn.vcn["vcn1"]: Refreshing state... [id=ocid1.vcn.oc1.eu-frankfurt-1.amaaaaaaic6ifviawy53vzv7ylnbovxzlk6gdl3wj62qt7pazvsl3pinvxiq]
module.virtual_machine.data.oci_identity_availability_domains.ads: Read complete after 1s [id=IdentityAvailabilityDomainsDataSource-2220574233]
module.virtual_network.oci_core_network_security_group.nsg["vcn1"]: Refreshing state... [id=ocid1.networksecuritygroup.oc1.eu-frankfurt-1.aaaaaaaaphiusldsxpmy7odws7mwaitxvfeu52ntgbb2vkwe7fzhvyckb45q]
module.virtual_network.oci_core_internet_gateway.igw["vcn1"]: Refreshing state... [id=ocid1.internetgateway.oc1.eu-frankfurt-1.aaaaaaaafkt7nrvasfyvu4a7daqfqskkfh4vmbqpye7qr35abqnhrumie32a]
module.virtual_network.oci_core_network_security_group_security_rule.nsg_rule["rule1"]: Refreshing state... [id=96F721]
module.virtual_network.oci_core_network_security_group_security_rule.nsg_rule["rule2"]: Refreshing state... [id=73C8D4]
module.virtual_network.oci_core_network_security_group_security_rule.nsg_rule["rule3"]: Refreshing state... [id=868C1D]
module.virtual_network.oci_core_route_table.rt["vcn1"]: Refreshing state... [id=ocid1.routetable.oc1.eu-frankfurt-1.aaaaaaaa5jyv5xby72ed73eqsxt3t7o6z7symzmk3we5rhpongsnakijdzba]
module.virtual_network.oci_core_subnet.subnet["subnet1"]: Refreshing state... [id=ocid1.subnet.oc1.eu-frankfurt-1.aaaaaaaatfy3s5otqei4lcl7czf6jk7bliptcfwx4e35otvnd5muldjqutea]
module.virtual_machine.oci_core_instance.vm["worker2"]: Refreshing state... [id=ocid1.instance.oc1.eu-frankfurt-1.antheljtic6ifvicwkkm6vc2zy2coshuuhmpsxewt2sgrwox5uxzq25kafga]
module.virtual_machine.oci_core_instance.vm["worker1"]: Refreshing state... [id=ocid1.instance.oc1.eu-frankfurt-1.antheljtic6ifvicyrvcdxqz6zmx6ahdsk44e4q23h6zabdlvo2csswwy57a]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create
  ~ update in-place

Terraform will perform the following actions:

  # module.cloudflare_dns.cloudflare_record.a_record["worker1"] will be created
  + resource "cloudflare_record" "a_record" {
      + allow_overwrite = false
      + created_on      = (known after apply)
      + hostname        = (known after apply)
      + id              = (known after apply)
      + metadata        = (known after apply)
      + modified_on     = (known after apply)
      + name            = "worker1"
      + proxiable       = (known after apply)
      + ttl             = (known after apply)
      + type            = "A"
      + value           = "130.162.52.123"
      + zone_id         = "db02d579021ff238991a645e755dfb8b"
    }

  # module.cloudflare_dns.cloudflare_record.a_record["worker2"] will be created
  + resource "cloudflare_record" "a_record" {
      + allow_overwrite = false
      + created_on      = (known after apply)
      + hostname        = (known after apply)
      + id              = (known after apply)
      + metadata        = (known after apply)
      + modified_on     = (known after apply)
      + name            = "worker2"
      + proxiable       = (known after apply)
      + ttl             = (known after apply)
      + type            = "A"
      + value           = "141.144.227.169"
      + zone_id         = "db02d579021ff238991a645e755dfb8b"
    }

  # module.virtual_network.oci_core_internet_gateway.igw["vcn1"] will be updated in-place
  ~ resource "oci_core_internet_gateway" "igw" {
      ~ defined_tags   = {
          - "Oracle-Tags.CreatedBy" = "default/petr.nemec@gmx.com" -> null
          - "Oracle-Tags.CreatedOn" = "2023-06-30T11:34:23.981Z" -> null
        }
        id             = "ocid1.internetgateway.oc1.eu-frankfurt-1.aaaaaaaafkt7nrvasfyvu4a7daqfqskkfh4vmbqpye7qr35abqnhrumie32a"
        # (7 unchanged attributes hidden)
    }

  # module.virtual_network.oci_core_route_table.rt["vcn1"] will be updated in-place
  ~ resource "oci_core_route_table" "rt" {
      ~ defined_tags   = {
          - "Oracle-Tags.CreatedBy" = "default/petr.nemec@gmx.com" -> null
          - "Oracle-Tags.CreatedOn" = "2023-06-30T11:34:25.302Z" -> null
        }
        id             = "ocid1.routetable.oc1.eu-frankfurt-1.aaaaaaaa5jyv5xby72ed73eqsxt3t7o6z7symzmk3we5rhpongsnakijdzba"
        # (6 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

Plan: 2 to add, 2 to change, 0 to destroy.
```

Plan saved to GH artifacts.

**Review by petr-jamf — DISMISSED** [review]

**Comment by germanium-git** [comment]
Terraform Plan:

```
module.cloudflare_dns.data.cloudflare_zones.zone: Reading...
module.cloudflare_dns.data.cloudflare_zones.zone: Read complete after 1s [id=db02d579021ff238991a645e755dfb8b]
oci_identity_compartment.k8s: Refreshing state... [id=ocid1.compartment.oc1..aaaaaaaa4bbfmz332ypqxr6icuitp54jj7czdp4qliuo575ytuqakppgtmra]
module.virtual_machine.data.oci_identity_availability_domains.ads: Reading...
module.virtual_network.oci_core_vcn.vcn["vcn1"]: Refreshing state... [id=ocid1.vcn.oc1.eu-frankfurt-1.amaaaaaaic6ifviawy53vzv7ylnbovxzlk6gdl3wj62qt7pazvsl3pinvxiq]
module.virtual_machine.data.oci_identity_availability_domains.ads: Read complete after 0s [id=IdentityAvailabilityDomainsDataSource-2220574233]
module.virtual_network.oci_core_network_security_group.nsg["vcn1"]: Refreshing state... [id=ocid1.networksecuritygroup.oc1.eu-frankfurt-1.aaaaaaaaphiusldsxpmy7odws7mwaitxvfeu52ntgbb2vkwe7fzhvyckb45q]
module.virtual_network.oci_core_internet_gateway.igw["vcn1"]: Refreshing state... [id=ocid1.internetgateway.oc1.eu-frankfurt-1.aaaaaaaafkt7nrvasfyvu4a7daqfqskkfh4vmbqpye7qr35abqnhrumie32a]
module.virtual_network.oci_core_network_security_group_security_rule.nsg_rule["rule3"]: Refreshing state... [id=868C1D]
module.virtual_network.oci_core_network_security_group_security_rule.nsg_rule["rule2"]: Refreshing state... [id=73C8D4]
module.virtual_network.oci_core_network_security_group_security_rule.nsg_rule["rule1"]: Refreshing state... [id=96F721]
module.virtual_network.oci_core_route_table.rt["vcn1"]: Refreshing state... [id=ocid1.routetable.oc1.eu-frankfurt-1.aaaaaaaa5jyv5xby72ed73eqsxt3t7o6z7symzmk3we5rhpongsnakijdzba]
module.virtual_network.oci_core_subnet.subnet["subnet1"]: Refreshing state... [id=ocid1.subnet.oc1.eu-frankfurt-1.aaaaaaaatfy3s5otqei4lcl7czf6jk7bliptcfwx4e35otvnd5muldjqutea]
module.virtual_machine.oci_core_instance.vm["worker2"]: Refreshing state... [id=ocid1.instance.oc1.eu-frankfurt-1.antheljtic6ifvicwkkm6vc2zy2coshuuhmpsxewt2sgrwox5uxzq25kafga]
module.virtual_machine.oci_core_instance.vm["worker1"]: Refreshing state... [id=ocid1.instance.oc1.eu-frankfurt-1.antheljtic6ifvicyrvcdxqz6zmx6ahdsk44e4q23h6zabdlvo2csswwy57a]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # module.cloudflare_dns.cloudflare_record.a_record["worker1"] will be created
  + resource "cloudflare_record" "a_record" {
      + allow_overwrite = false
      + created_on      = (known after apply)
      + hostname        = (known after apply)
      + id              = (known after apply)
      + metadata        = (known after apply)
      + modified_on     = (known after apply)
      + name            = "worker1"
      + proxiable       = (known after apply)
      + ttl             = (known after apply)
      + type            = "A"
      + value           = "130.162.52.123"
      + zone_id         = "db02d579021ff238991a645e755dfb8b"
    }

  # module.cloudflare_dns.cloudflare_record.a_record["worker2"] will be created
  + resource "cloudflare_record" "a_record" {
      + allow_overwrite = false
      + created_on      = (known after apply)
      + hostname        = (known after apply)
      + id              = (known after apply)
      + metadata        = (known after apply)
      + modified_on     = (known after apply)
      + name            = "worker2"
      + proxiable       = (known after apply)
      + ttl             = (known after apply)
      + type            = "A"
      + value           = "141.144.227.169"
      + zone_id         = "db02d579021ff238991a645e755dfb8b"
    }

Plan: 2 to add, 0 to change, 0 to destroy.
```

Plan saved to GH artifacts.

**Comment by germanium-git** [comment]
Terraform Plan:

```
module.cloudflare_dns.data.cloudflare_zone.zone: Reading...
module.cloudflare_dns.data.cloudflare_zone.zone: Read complete after 0s [id=7d3f63ac039666ab600b5796c54e7ba6]
oci_identity_compartment.k8s: Refreshing state... [id=ocid1.compartment.oc1..aaaaaaaa4bbfmz332ypqxr6icuitp54jj7czdp4qliuo575ytuqakppgtmra]
module.virtual_machine.data.oci_identity_availability_domains.ads: Reading...
module.virtual_network.oci_core_vcn.vcn["vcn1"]: Refreshing state... [id=ocid1.vcn.oc1.eu-frankfurt-1.amaaaaaaic6ifviawy53vzv7ylnbovxzlk6gdl3wj62qt7pazvsl3pinvxiq]
module.virtual_machine.data.oci_identity_availability_domains.ads: Read complete after 0s [id=IdentityAvailabilityDomainsDataSource-2220574233]
module.virtual_network.oci_core_network_security_group.nsg["vcn1"]: Refreshing state... [id=ocid1.networksecuritygroup.oc1.eu-frankfurt-1.aaaaaaaaphiusldsxpmy7odws7mwaitxvfeu52ntgbb2vkwe7fzhvyckb45q]
module.virtual_network.oci_core_internet_gateway.igw["vcn1"]: Refreshing state... [id=ocid1.internetgateway.oc1.eu-frankfurt-1.aaaaaaaafkt7nrvasfyvu4a7daqfqskkfh4vmbqpye7qr35abqnhrumie32a]
module.virtual_network.oci_core_route_table.rt["vcn1"]: Refreshing state... [id=ocid1.routetable.oc1.eu-frankfurt-1.aaaaaaaa5jyv5xby72ed73eqsxt3t7o6z7symzmk3we5rhpongsnakijdzba]
module.virtual_network.oci_core_network_security_group_security_rule.nsg_rule["rule1"]: Refreshing state... [id=96F721]
module.virtual_network.oci_core_network_security_group_security_rule.nsg_rule["rule2"]: Refreshing state... [id=73C8D4]
module.virtual_network.oci_core_network_security_group_security_rule.nsg_rule["rule3"]: Refreshing state... [id=868C1D]
module.virtual_network.oci_core_subnet.subnet["subnet1"]: Refreshing state... [id=ocid1.subnet.oc1.eu-frankfurt-1.aaaaaaaatfy3s5otqei4lcl7czf6jk7bliptcfwx4e35otvnd5muldjqutea]
module.virtual_machine.oci_core_instance.vm["worker2"]: Refreshing state... [id=ocid1.instance.oc1.eu-frankfurt-1.antheljtic6ifvicwkkm6vc2zy2coshuuhmpsxewt2sgrwox5uxzq25kafga]
module.virtual_machine.oci_core_instance.vm["worker1"]: Refreshing state... [id=ocid1.instance.oc1.eu-frankfurt-1.antheljtic6ifvicyrvcdxqz6zmx6ahdsk44e4q23h6zabdlvo2csswwy57a]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # module.cloudflare_dns.cloudflare_record.a_record["worker1"] will be created
  + resource "cloudflare_record" "a_record" {
      + allow_overwrite = false
      + created_on      = (known after apply)
      + hostname        = (known after apply)
      + id              = (known after apply)
      + metadata        = (known after apply)
      + modified_on     = (known after apply)
      + name            = "worker1"
      + proxiable       = (known after apply)
      + ttl             = (known after apply)
      + type            = "A"
      + value           = "130.162.52.123"
      + zone_id         = "7d3f63ac039666ab600b5796c54e7ba6"
    }

  # module.cloudflare_dns.cloudflare_record.a_record["worker2"] will be created
  + resource "cloudflare_record" "a_record" {
      + allow_overwrite = false
      + created_on      = (known after apply)
      + hostname        = (known after apply)
      + id              = (known after apply)
      + metadata        = (known after apply)
      + modified_on     = (known after apply)
      + name            = "worker2"
      + proxiable       = (known after apply)
      + ttl             = (known after apply)
      + type            = "A"
      + value           = "141.144.227.169"
      + zone_id         = "7d3f63ac039666ab600b5796c54e7ba6"
    }

Plan: 2 to add, 0 to change, 0 to destroy.
```

Plan saved to GH artifacts.

**Review by petr-jamf — APPROVED** [review]

**Comment by germanium-git** [comment]
Terraform Apply:

```
module.cloudflare_dns.cloudflare_record.a_record["worker2"]: Creating...
module.cloudflare_dns.cloudflare_record.a_record["worker1"]: Creating...
module.cloudflare_dns.cloudflare_record.a_record["worker2"]: Creation complete after 1s [id=7b5a79ce475f54e4ce5bc1b28e907dac]
module.cloudflare_dns.cloudflare_record.a_record["worker1"]: Creation complete after 1s [id=85b2b2202a344df108f0d1f90ab7a0c6]

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.

Outputs:

vm_public_ip = {
  "worker1" = "130.162.52.123"
  "worker2" = "141.144.227.169"
}
```

**Pull request merged**
